dist: bionic

language: c

compiler:
    - gcc

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake
            - pkgconf
            - wget
            - ca-certificates
            - openssl
            - libssl-dev
            - udev
            - gettext
            - python3
            - python3-pip
            - python3-setuptools
            - python3-wheel
            - ninja-build
            - libconfig-dev
            - libpam0g-dev
            - valgrind

env:
    matrix:
        - BUILD_TYPE=debug   COVERAGE=true  CHECK_OPTS=
        - BUILD_TYPE=debug   COVERAGE=false CHECK_OPTS=--wrap='valgrind --error-exitcode=42'
        - BUILD_TYPE=release COVERAGE=false CHECK_OPTS=
        - BUILD_TYPE=minsize COVERAGE=false CHECK_OPTS=
              

before_install:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu
    - sudo pip3 install --system meson
    - bash <(curl -s https://raw.githubusercontent.com/falk-werner/install_deps/main/install_deps.sh) -s

before_script:
    - meson -Dbuildtype=$BUILD_TYPE -Db_coverage=$COVERAGE build
    - cd build
    - ninja

script:
    - meson test --print-errorlogs $CHECK_OPTS

after_success:
    - bash <(curl -s https://codecov.io/bash)  